create table person (
    id bigint generated by default as identity,
    cpf varchar(255),
    date_birth date,
    employee boolean not null,
    name varchar(255),
    position varchar(255),
    primary key (id)
)