create table project (
   id bigint generated by default as identity,
    budget numeric(19,2) not null,
    date_end date,
    date_estimated_end date not null,
    date_start date not null,
    description varchar(1000),
    name varchar(100) not null,
    risk varchar(10),
    status varchar(50) not null,
    primary key (id)
)