create table project (
    id bigint generated by default as identity,
    budget numeric(19,2),
    date_end date,
    date_estimated_end date,
    date_start date,
    description varchar(255),
    name varchar(255),
    risk varchar(255),
    status varchar(255),
    primary key (id)
)