server:
  port: 8080
  servlet:
    context-path: /project-manager

spring:
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  datasource:
    url: jdbc:postgresql://db-postgres:5432/dev
    username: pm
    password: pm@123
  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    validate-on-migrate: true